### ISSUE TITLE
ModuleNotFoundError: No module named 'cvt2utf'

### ISSUE THREAD

**Issue by ivysrono** [x1angli/convert2utf#1]
Python 3.6.1
`pip install convert2utf`
`from cvt2utf import Convert2Utf8`

```
    from cvt2utf import Convert2Utf8
ModuleNotFoundError: No module named 'cvt2utf'
```

**Comment by droudy** [comment]
I believe there is an issue with the installation through pip, but you can work around it by cloning the repo directly into the site-packages directory of your python installation. For example with a virtual environment by the name of `example_env` you would do the following: 
```
cd example_env/lib/python3.5/site-packages
git clone https://github.com/x1angli/convert2utf.git
```

Then in python:
```
>>> from convert2utf.cvt2utf import Convert2Utf8
```

**Comment by x1angli** [comment]
Thanks for the feedback. Let me know if the issue persists.

**Comment by ivysrono** [comment]
No pypi update yet?

**Comment by x1angli** [comment]
I am in the middle of updating pypi and it seems `ImportError: No module named 'cvt2utf'` is still there...

**Comment by x1angli** [comment]
I just updated the source code, made a new release sdist, and uploaded it onto PyPI.  It should be working now. @ivysrono  

Please run `pip install convert2utf -U` or `pip install convert2utf -U  -i https://pypi.python.org/pypi` to make sure it's **v0.8.5** or later version. And then you're good to go.
