### ISSUE TITLE
把latin_1的优先级放到GB2312的解码尝试前，会导致GB2312编码的文件转换后错误。

### ISSUE THREAD

**Issue by jimmyleocn** [x1angli/convert2utf#9]
bytedata.decode 采用 latin_1 的方式，GB2312 编码的文件也能通过。

**Comment by x1angli** [comment]
@jimmyleocn 

的确是一个重大bug，已经修复，感谢指正。

欢迎提其它宝贵意见

**Comment by x1angli** [comment]
@jimmyleocn 刚刚做了一次大改版。欢迎测试并提宝贵意见建议，谢谢

**Comment by shaunthegeek** [comment]
此问题仍然存在，看起来是「修复了，但没有发版」？

建议：按照 git 规范，使用 git tag 进行发版。

<img width="829" alt="image" src="https://github.com/x1angli/cvt2utf/assets/4971414/c98f3234-b294-4ab5-839e-f1cc4badd6aa">

<img width="935" alt="image" src="https://github.com/x1angli/cvt2utf/assets/4971414/08d27766-2035-4383-badf-f8dd36e9a936">

<img width="1165" alt="image" src="https://github.com/x1angli/cvt2utf/assets/4971414/0e1bf2ba-eb3c-44c5-b22b-fd063f207e77">

<img width="589" alt="image" src="https://github.com/x1angli/cvt2utf/assets/4971414/b8010aa4-a0c4-4233-9e5a-635d7daab443">

<img width="990" alt="image" src="https://github.com/x1angli/cvt2utf/assets/4971414/4efc683c-49ba-4f5d-ac2b-a5363db3002f">
